// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqBkaJEiVBBis6nLk2SShQdYZTZEZfkpw',
    appId: '1:336514695273:web:50b4ac497bb459e60a22f8',
    messagingSenderId: '336514695273',
    projectId: 'autostop-acf5d',
    authDomain: 'autostop-acf5d.firebaseapp.com',
    databaseURL:
        'https://autostop-acf5d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'autostop-acf5d.appspot.com',
    measurementId: 'G-ZLV7KVTFKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjgQwhgaJd03RjPuqI31hZIknSVFncIN0',
    appId: '1:336514695273:android:8feca309439628970a22f8',
    messagingSenderId: '336514695273',
    projectId: 'autostop-acf5d',
    databaseURL:
        'https://autostop-acf5d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'autostop-acf5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-e7ixfjtkebGqIJpqJOzUvI9vUJgqEGg',
    appId: '1:336514695273:ios:7886068dc77eaf5b0a22f8',
    messagingSenderId: '336514695273',
    projectId: 'autostop-acf5d',
    databaseURL:
        'https://autostop-acf5d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'autostop-acf5d.appspot.com',
    iosClientId:
        '336514695273-rl7ha469celn1pu4rpo3q880m9tdfgvd.apps.googleusercontent.com',
    iosBundleId: 'com.cousseaujimmy.autostop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-e7ixfjtkebGqIJpqJOzUvI9vUJgqEGg',
    appId: '1:336514695273:ios:7886068dc77eaf5b0a22f8',
    messagingSenderId: '336514695273',
    projectId: 'autostop-acf5d',
    databaseURL:
        'https://autostop-acf5d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'autostop-acf5d.appspot.com',
    iosClientId:
        '336514695273-rl7ha469celn1pu4rpo3q880m9tdfgvd.apps.googleusercontent.com',
    iosBundleId: 'com.cousseaujimmy.autostop',
  );
}
